name: Publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "Bookkeepersmc/m2"
          ref: master
          path: "./m2/"
          token: ${{ secrets.GIT_PAT }}
      - uses: gradle/wrapper-validation-action@v2

      # Generate the build number based on tags to allow per branch build numbers, not something github provides by default.
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
          prefix: "build/${{ github.ref }}"

      - run: ./gradlew build publish -x test --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          add: '["./com/", "./notebook-loom/"]'
          default_author: github_actions
          cwd: "./m2/"
          message: "Publish loom (stable)"
